# Generated by Django 3.0.8 on 2020-10-23 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrylog',
            options={'verbose_name': '重置密码临时表', 'verbose_name_plural': '重置密码临时表'},
        ),
        migrations.RemoveField(
            model_name='registrylog',
            name='code',
        ),
        migrations.AddField(
            model_name='registrylog',
            name='slug',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, verbose_name='Slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrylog',
            name='code_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Slug有效期'),
        ),
    ]
