# Generated by Django 3.0.8 on 2020-10-23 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201023_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('slug', models.CharField(max_length=6, verbose_name='Slug')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('code_time', models.DateTimeField(auto_now=True, verbose_name='Slug有效期')),
            ],
            options={
                'verbose_name': '重置密码临时表',
                'verbose_name_plural': '重置密码临时表',
            },
        ),
        migrations.AlterModelOptions(
            name='registrylog',
            options={'verbose_name': '注册临时表', 'verbose_name_plural': '注册临时表'},
        ),
        migrations.RemoveField(
            model_name='registrylog',
            name='slug',
        ),
        migrations.AddField(
            model_name='registrylog',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, max_length=6, verbose_name='验证码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrylog',
            name='code_time',
            field=models.DateTimeField(auto_now=True, verbose_name='验证码有效期'),
        ),
    ]
