# Generated by Django 3.0.8 on 2020-10-23 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201023_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetlog',
            name='ensure',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='确认码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='passwordresetlog',
            name='slug',
            field=models.CharField(max_length=128, verbose_name='Slug'),
        ),
    ]
