# Generated by Django 3.0.8 on 2020-11-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userinfo_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlyCodeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('code', models.CharField(max_length=8, verbose_name='验证码')),
                ('operate_time', models.DateTimeField(auto_now_add=True, verbose_name='初次操作时间')),
                ('code_time', models.DateTimeField(auto_now=True, verbose_name='验证码有效期')),
            ],
            options={
                'verbose_name': '唯一码临时表',
                'verbose_name_plural': '唯一码临时表',
            },
        ),
        migrations.AlterField(
            model_name='passwordresetlog',
            name='operate_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='初次操作时间'),
        ),
        migrations.AlterField(
            model_name='registrylog',
            name='code',
            field=models.CharField(max_length=8, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='registrylog',
            name='operate_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='初次操作时间'),
        ),
    ]
