# Generated by Django 3.0.8 on 2020-11-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201106_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户唯一标识码'),
        ),
    ]
