# Generated by Django 3.0.8 on 2020-10-28 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='version',
            field=models.CharField(default='1.0.0', max_length=30, verbose_name='版本号'),
        ),
    ]
