# Generated by Django 3.0.8 on 2020-10-28 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_article_version'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '插件内容', 'verbose_name_plural': '插件内容'},
        ),
    ]
