# Generated by Django 3.0.8 on 2020-10-29 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20201028_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='iswrite',
            field=models.BooleanField(default=False, verbose_name='是否已撰写示例'),
        ),
    ]
