# Generated by Django 3.0.8 on 2020-11-06 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('docs', '0005_auto_20201029_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlugIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='接口')),
                ('isvalid', models.BooleanField(default=True, verbose_name='可用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aurls', to='docs.Article', verbose_name='关联文章')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL, verbose_name='创作者')),
            ],
            options={
                'verbose_name': '接口开放',
                'verbose_name_plural': '接口开放',
            },
        ),
        migrations.CreateModel(
            name='LimitLinkPlugIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.PositiveIntegerField(default=100, verbose_name='剩余调用次数')),
                ('continue_times', models.PositiveIntegerField(default=0, verbose_name='续约次数')),
                ('islegal', models.BooleanField(default=False, verbose_name='禁用')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plimits', to='docs.PlugIn', verbose_name='接口')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ulimits', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '关联调用',
                'verbose_name_plural': '关联调用',
            },
        ),
    ]
