# Generated by Django 2.2.1 on 2020-11-06 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_limitlinkplugin_plugin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '接口文章', 'verbose_name_plural': '接口文章'},
        ),
        migrations.AlterModelOptions(
            name='plugin',
            options={'verbose_name': '接口注册', 'verbose_name_plural': '接口注册'},
        ),
        migrations.AlterField(
            model_name='plugin',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aurls', to='docs.Article', verbose_name='关联文章'),
        ),
        migrations.AlterField(
            model_name='plugin',
            name='url',
            field=models.URLField(unique=True, verbose_name='接口'),
        ),
    ]
