# Generated by Django 2.2.1 on 2020-11-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20201106_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='plugin',
            name='only_code',
            field=models.CharField(default=1, max_length=32, verbose_name='接口唯一标识'),
            preserve_default=False,
        ),
    ]
