# Generated by Django 3.0.8 on 2020-11-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_plugin_only_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitlinkplugin',
            name='access_code',
            field=models.CharField(default=0, max_length=8, verbose_name='授权码'),
            preserve_default=False,
        ),
    ]
