# Generated by Django 2.2.1 on 2020-11-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0010_auto_20201107_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitlinkplugin',
            name='access_code',
            field=models.CharField(max_length=8, verbose_name='授权码'),
        ),
    ]
