# Generated by Django 2.2.1 on 2020-10-24 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('abstract', models.CharField(max_length=100, verbose_name='摘要')),
                ('label', models.CharField(max_length=100, verbose_name='标签')),
                ('level', models.CharField(choices=[('a', 'A级'), ('b', 'B级'), ('c', 'C级'), ('d', 'D级'), ('e', 'E级'), ('f', 'F级'), ('g', 'G级'), ('h', 'H级'), ('i', 'I级')], default='a', max_length=1, verbose_name='文章评级')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('isvisible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('url_path', models.CharField(blank=True, default='', max_length=60, verbose_name='页面绑定')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='支持率')),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='a_articles', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='r_articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='支持率')),
                ('isvisible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='blog.Article', verbose_name='文章')),
                ('parent_remark', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_remark', to='blog.Remark', verbose_name='上级评论')),
                ('remarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rremarks', to=settings.AUTH_USER_MODEL, verbose_name='评论人')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='板块名')),
                ('description', models.TextField(verbose_name='板块描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '板块',
                'verbose_name_plural': '板块',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_articles', to='blog.Board', verbose_name='所属板块'),
        ),
    ]
