# Generated by Django 2.2.1 on 2020-10-27 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_remark_isroot'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='level',
            field=models.CharField(choices=[('A', '一般'), ('B', '重要'), ('C', '紧急')], default='A', max_length=1, verbose_name='紧急情况'),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='建议内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('suggester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggests', to=settings.AUTH_USER_MODEL, verbose_name='建议人')),
            ],
            options={
                'verbose_name': '建议',
                'verbose_name_plural': '建议',
            },
        ),
    ]
