# Generated by Django 3.0.8 on 2020-10-28 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201028_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isgood',
            field=models.BooleanField(default=False, verbose_name='是否精选'),
        ),
    ]
