# Generated by Django 3.0.8 on 2020-10-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_pluginsamples'),
    ]

    operations = [
        migrations.AddField(
            model_name='pluginsamples',
            name='pluginPk',
            field=models.PositiveIntegerField(default=0, verbose_name='父pk'),
            preserve_default=False,
        ),
    ]
