# Generated by Django 3.0.8 on 2020-10-29 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201029_1016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pluginsamples',
            options={'verbose_name': '范例', 'verbose_name_plural': '范例'},
        ),
    ]
