# Generated by Django 2.2.1 on 2020-10-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201029_1643'),
    ]

    operations = [
        migrations.CreateModel(
            name='Change',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='变更内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '变更',
                'verbose_name_plural': '变更',
            },
        ),
        migrations.AddField(
            model_name='suggestion',
            name='votes',
            field=models.PositiveIntegerField(default=0, verbose_name='投票'),
        ),
    ]
